require_relative "authClient"
require_relative "../constants"

module Cryptomarket
    module Websocket

        # TradingClient connects via websocket to cryptomarket to enable the user to manage orders. uses SHA256 as auth method and authenticates automatically.

        class TradingClient < AuthClient
            # Creates a new client
            # ==== Params
            # +string+ +apiKey+:: the user api key
            # +string+ +apiSecret+:: the user api secret
            # +Integer+ +window+:: Maximum difference between the creation of the request and the moment of request processing in milliseconds. Max is 60_000. Defaul is 10_000
            def initialize(apiKey:, apiSecret:, window:nil)
                reports = "reports"
                super(
                    url:"wss://api.exchange.cryptomkt.com/api/3/ws/trading",
                    apiKey:apiKey,
                    apiSecret:apiSecret,
                    window:window,
                    subscriptionKeys:{
                        "spot_subscribe" => [reports, Args::NotificationType::COMMAND],
                        "spot_unsubscribe" => [reports, Args::NotificationType::COMMAND],
                        "spot_orders" => [reports, Args::NotificationType::SNAPSHOT],
                        "spot_order" => [reports, Args::NotificationType::UPDATE]
                    })
            end

            # subscribe to a feed of execution reports of the user's orders
            #
            # https://api.exchange.cryptomkt.com/#socket-spot-trading
            #
            # ==== Params
            # +Proc+ +callback+:: A +Proc+ that recieves notifications as a list of reports, and the type of notification (either 'snapshot' or 'update')
            # +Proc+ +resultCallback+:: Optional. A +Proc+ called with a boolean value, indicating the success of the subscription

            def subscribe_to_reports(callback:, resultCallback:nil)
                interceptor = Proc.new {|notification, type|
                  if type == Args::NotificationType::SNAPSHOT
                    callback.call(notification, type)
                  else
                    callback.call([notification], type)
                  end
                }
                sendSubscription('spot_subscribe', interceptor, {}, resultCallback)
            end

            # stop recieveing the report feed subscription
            #
            # https://api.exchange.cryptomkt.com/#socket-spot-trading
            #
            # ==== Params
            # +Proc+ +callback+:: Optional. A +Proc+ called with a boolean value, indicating the success of the unsubscription

            def unsubscribe_to_reports(callback:nil)
              sendUnsubscription('spot_unsubscribe', callback, nil)
            end

            # Get the user's active spot orders
            #
            # https://api.exchange.cryptomkt.com/#get-active-spot-orders
            #
            # ==== Params
            # +Proc+ +callback+:: A +Proc+ called with a list of reports for all active spot orders

            def get_active_spot_orders(callback:)
              sendById('spot_get_orders', callback)
            end

            # Creates a new spot order
            #
            # For fee, for price accuracy and quantity, and for order status information see the api docs at https://api.exchange.cryptomkt.com/#create-new-spot-order
            #
            # https://api.exchange.cryptomkt.com/#place-new-spot-order
            #
            # ==== Params
            # +String+ +symbol+:: Trading symbol
            # +String+ +side+:: Either 'buy' or 'sell'
            # +String+ +quantity+:: Order quantity
            # +String+ +client_order_id+:: Optional. If given must be unique within the trading day, including all active orders. If not given, is generated by the server
            # +String+ +type+:: Optional. 'limit', 'market', 'stopLimit', 'stopMarket', 'takeProfitLimit' or 'takeProfitMarket'. Default is 'limit'
            # +String+ +time_in_force+:: Optional. 'GTC', 'IOC', 'FOK', 'Day', 'GTD'. Default to 'GTC'
            # +String+ +price+:: Optional. Required for 'limit' and 'stopLimit'. limit price of the order
            # +String+ +stop_price+:: Optional. Required for 'stopLimit' and 'stopMarket' orders. stop price of the order
            # +String+ +expire_time+:: Optional. Required for orders with timeInForce = GDT
            # +bool+ +strict_validate+:: Optional. If False, the server rounds half down for tickerSize and quantityIncrement. Example of ETHBTC: tickSize = '0.000001', then price '0.046016' is valid, '0.0460165' is invalid
            # +bool+ +post_only+:: Optional. If True, your post_only order causes a match with a pre-existing order as a taker, then the order will be cancelled
            # +String+ +take_rate+:: Optional. Liquidity taker fee, a fraction of order volume, such as 0.001 (for 0.1% fee). Can only increase the fee. Used for fee markup.
            # +String+ +make_rate+:: Optional. Liquidity provider fee, a fraction of order volume, such as 0.001 (for 0.1% fee). Can only increase the fee. Used for fee markup.
            # +Proc+ +callback+:: A +Proc+ called with the report of the created order

            def create_spot_order(
              symbol:,
              side:,
              quantity:,
              client_order_id:nil,
              type:nil,
              time_in_force:nil,
              price:nil,
              stop_price:nil,
              expire_time:nil,
              strict_validate:nil,
              post_only:nil,
              take_rate:nil,
              make_rate:nil,
              callback:nil
            )
              sendById('spot_new_order', callback, {
                client_order_id:client_order_id,
                symbol:symbol,
                side:side,
                quantity:quantity,
                type:type,
                time_in_force:time_in_force,
                price:price,
                stop_price:stop_price,
                expire_time:expire_time,
                strict_validate:strict_validate,
                post_only:post_only,
                take_rate:take_rate,
                make_rate:make_rate
              })
            end

            # creates a list of spot orders
            #
            # = Types or contingency
            # - Contingency.ALL_OR_NONE (Contingency.AON)
            # - Contingency.ONE_CANCEL_OTHER (Contingency.OCO)
            # - Contingency.ONE_TRIGGER_ONE_CANCEL_OTHER (Contingency.OTOCO)
            #
            # = Restriction in the number of orders:
            # - An AON list must have 2 or 3 orders
            # - An OCO list must have 2 or 3 orders
            # - An OTOCO must have 3 or 4 orders
            #
            # = Symbol restrictions
            # - For an AON order list, the symbol code of orders must be unique for each order in the list.
            # - For an OCO order list, there are no symbol code restrictions.
            # - For an OTOCO order list, the symbol code of orders must be the same for all orders in the list (placing orders in different order books is not supported).
            #
            # = OrderType restrictions
            # - For an AON order list, orders must be OrderType.LIMIT or OrderType.Market
            # - For an OCO order list, orders must be OrderType.LIMIT, OrderType.STOP_LIMIT, OrderType.STOP_MARKET, OrderType.TAKE_PROFIT_LIMIT or OrderType.TAKE_PROFIT_MARKET.
            # - An OCO order list cannot include more than one limit order (the same
            # applies to secondary orders in an OTOCO order list).
            # - For an OTOCO order list, the first order must be OrderType.LIMIT, OrderType.MARKET, OrderType.STOP_LIMIT, OrderType.STOP_MARKET, OrderType.TAKE_PROFIT_LIMIT or OrderType.TAKE_PROFIT_MARKET.
            # - For an OTOCO order list, the secondary orders have the same restrictions as an OCO order
            # - Default is OrderType.Limit
            #
            # https://api.exchange.cryptomkt.com/#create-new-spot-order-list-2
            #
            # ==== Params
            # +String+ +order_list_id+:: order list identifier. If ommited, it will be generated by the system. Must be equal to the client order id of the first order in the request
            # +String+ +contingency_type+:: order list type. allOrNone, oneCancelOther or oneTriggerOneCancelOther
            # +Array[]+ +orders+:: the list of orders
            # +Proc+ +callback+:: A +Proc+ called with a list of reports of the created orders

            def create_spot_order_list(
              orders:,
              contingency_type:,
              order_list_id:nil,
              callback:nil
            )
              sendById('spot_new_order_list', callback, {
                orders:orders,
                contingency_type:contingency_type,
                order_list_id:order_list_id,
              })
            end

            # cancels a spot order
            #
            # https://api.exchange.cryptomkt.com/#cancel-spot-order-2
            #
            # ==== Params
            # +String+ +client_order_id+:: the client order id of the order to cancel
            # +Proc+ +callback+:: A +Proc+ called with a list of reports of the canceled orders
            def cancel_spot_order(client_order_id:, callback:nil)
                sendById('spot_cancel_order', callback, {client_order_id:client_order_id})
            end

            # cancel all active spot orders and returns the ones that could not be canceled
            #
            # https://api.exchange.cryptomkt.com/#cancel-spot-orders
            #
            # ==== Params
            # +Proc+ +callback+:: A +Proc+ called with a report of the canceled order

            def cancel_spot_orders(callback:nil)
              sendById('spot_cancel_orders', callback)
            end

            # Get the user's spot trading balance for all currencies with balance
            #
            # Requires the "Orderbook, History, Trading balance" API key Access Right
            #
            # https://api.exchange.cryptomkt.com/#get-spot-trading-balance
            #
            # ==== Params
            # +Proc+ +callback+:: A +Proc+ called with a list of the trading balances
            def get_spot_trading_balances(callback:)
              sendById('spot_balances', callback)
            end

            # Get the user spot trading balance of a currency
            #
            # Requires the "Orderbook, History, Trading balance" API key Access Right
            #
            # https://api.exchange.cryptomkt.com/#get-spot-trading-balance
            #
            # ==== Params
            # +String+ +currency+:: The currency code to query the balance
            # +Proc+ +callback+:: A +Proc+ called with a trading balance
            def get_spot_trading_balance(currency:, callback:)
              sendById('spot_balance', callback, {currency:currency})
            end

            # changes the parameters of an existing order, quantity or price
            #
            # https://api.exchange.cryptomkt.com/#cancel-replace-spot-order
            #
            # ==== Params
            # +String+ +client_order_id+:: the client order id of the order to change
            # +String+ +new_client_order_id+:: the new client order id for the modified order. must be unique within the trading day
            # +String+ +quantity+:: new order quantity
            # +String+ +price+:: new order price
            # ++ +strict_validate+::  price and quantity will be checked for the incrementation with tick size and quantity step. See symbol's tick_size and quantity_increment
            # +Proc+ +callback+:: A +Proc+ called with the new version of the order
            def replace_spot_order(
              client_order_id:,
              new_client_order_id:,
              quantity:,
              price:,
              strict_validate:nil,
              callback:nil
            )
              sendById('spot_replace_order', callback, {
                client_order_id:client_order_id,
                new_client_order_id:new_client_order_id,
                quantity:quantity,
                price:price,
                strict_validate:strict_validate
              })
            end

            # Get the personal trading commission rates for all symbols
            #
            # Requires the "Place/cancel orders" API key Access Right
            #
            # https://api.exchange.cryptomkt.com/#get-all-trading-commission
            #
            # ==== Params
            # +Proc+ +callback+:: A +Proc+ called with a list of commissions for the user
            def get_spot_commissions(callback:)
              sendById('spot_fees', callback)
            end

            # Get the personal trading commission rate of a symbol
            #
            # Requires the "Place/cancel orders" API key Access Right
            #
            # https://api.exchange.cryptomkt.com/#get-trading-commission
            #
            # ==== Params
            # +String+ +symbol+:: The symbol of the commission rate
            # +Proc+ +callback+:: A +Proc+ called with a commission for a symbol for the user

            def get_spot_commission_of_symbol(symbol:, callback:)
              sendById('spot_fee', callback, {symbol:symbol})
            end
        end
    end
end